### ISSUE TITLE
Example doesn't work? [Bug on Domain class]

### ISSUE THREAD

**Issue by fernandolkf** [amogorkon/fuzzylogic#12] opened 2021-05-19 20:40 UTC
I tried to reproduce this example from the docs locally

```python
from fuzzylogic.classes import Domain
from fuzzylogic.functions import bounded_sigmoid

T = Domain("temperature", 0, 100)
T.cold = bounded_sigmoid(5,15, inverse=True)
T.cold.plot()
T.hot = bounded_sigmoid(20, 40)
T.hot.plot()
T.warm = ~T.hot & ~T.cold
T.warm.plot()
T(10)
```

The docs are deprecated, as the package is now called `fuzzylogic` instead of `fuzzy` but when I tried to execute this code I got this exception:

```bash
Traceback (most recent call last):

  File "/Users/suporte/miniconda3/envs/image-quality-lib/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-27-4457960f5d30>", line 1, in <module>
    from fuzzylogic.classes import Domain

  File "/Users/suporte/miniconda3/envs/image-quality-lib/lib/python3.7/site-packages/fuzzylogic/classes.py", line 420
    if (x := min(actual_values[k] for k in K if k in actual_values)) > 0]
          ^
SyntaxError: invalid syntax
```

Is there any solution or alternative for the class package?

**Comment by amogorkon** [comment] 2021-05-19 22:08
Hi,
it's not a bug. The walrus operator was introduced in python 3.8, you're using 3.7 which doesn't support this syntax.
It's not a crucial detail, I could change the implementation to be backwards compatible or I could update the requirements, which do you prefer?

**Comment by fernandolkf** [comment] 2021-05-19 22:26
Hi @amogorkon ! Thanks for the fast reply! I don't have any problem with updating my python to 3.8. Maybe being backwards compatible could expand which projects can use your lib so it's up to you ;)

**Comment by amogorkon** [comment] 2021-05-20 11:28
Well, 3.8 is pretty much standard in python3 land currently, so it's easiest to update requirements.

**Comment by amogorkon** [comment] 2021-05-20 11:30
Can we close the issue?

**Comment by fernandolkf** [comment] 2021-05-20 16:39
Sure! Sorry for the false alarm and thank you for the lib and your reply

**Closed** 2021-05-27 12:15 UTC
